<?php
	$default_mime_types = array(
						"jpeg" => "image/jpeg",
						"tiff" => "image/tiff",
						"jpg" => "image/jpg",
						"png" => "image/png",
						"gif" => "image/gif",
						"ico" => "image/vnd.microsoft.icon",
						"doc" => "application/msword",
						"xls" => "application/vnd.ms-excel",
						"docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
						"xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
						"txt" => "text/plain",
						"csv" => "text/csv",
						"zip" => "application/zip",
						"gzip" => "application/gzip",
						"rar" => "application/x-rar-compressed",
						"odf" => array("application/vnd.oasis.opendocument.text",
										"application/vnd.oasis.opendocument.spreadsheet",
										"application/vnd.oasis.opendocument.presentation",
										"application/vnd.oasis.opendocument.graphics"),
						"pdf" => "application/pdf",
						"powerpoint" => array("application/vnd.ms-powerpoint",
												"application/vnd.openxmlformats-officedocument.presentationml.presentation"),
						"mpeg" => array("audio/mpeg","video/mpeg"),
						"mp4" => array("audio/mp4","video/mp4"),
						"ogg" => array("audio/ogg","video/ogg","application/ogg"),
					);
?>